### ISSUE TITLE
Dataset 

### ISSUE THREAD

**Issue by bharadwajdhornala** [happylun/SketchModeling#12]
Hi @happylun Can you please share the Training dataset link? The link you shared in README is not working.

**Comment by happylun** [comment]
Hi. Sorry about the link issue. I just fixed those links. You should be able to download the files listed on this page now:
https://github.com/happylun/SketchModeling/tree/master/Network#how-to-run

**Comment by bharadwajdhornala** [comment]
Thanks @happylun
