### ISSUE TITLE
The testing data files can not be opened

### ISSUE THREAD

**Issue by wangqiang9** [happylun/SketchModeling#16]
The URL"Download testing data files [here](https://people.cs.umass.edu/~zlun/papers/SketchModeling/TestingData.7z)" can not be opened!
"The requested URL /~zlun/papers/SketchModeling/TestingData.7z was not found on this server."

**Comment by happylun** [comment]
You can download all data from this project page: https://people.cs.umass.edu/~kalo/papers/SketchModeling/

**Comment by wangqiang9** [comment]
The problem is sloved, thank you very much.
