### ISSUE TITLE
The method of rendering the ground truth of normal/depth map

### ISSUE THREAD

**Issue by LiuZhenyan-Wuzhong** [happylun/SketchModeling#17]
Hello, I have used your TestingData to predict normal/depth maps and fused them together to make mesh model. Absolutely, it works well.
Now, I am trying to training the network with my own input and ground truth(normal/depth map). I used blender to render the ground truth, but the result is different with your dataset(as below pictures). What's more, they makes no sense in the fusing part(as below pictures).
I'd like to ask you about the method of your rendering the groundtruth. Or can you share me the type or criteria(to some degree, what I mean is the direction of every color meaning) of your normal graph and I am going to map my normal pictures to yours.
Extremely thank you!!!

**Comment by happylun** [comment]
Hi, please see this thread for how the normal/depth information is encoded in the image: https://github.com/happylun/SketchModeling/issues/15#issuecomment-640281599

**Comment by LiuZhenyan-Wuzhong** [comment]
Your normal map(groundtruth) from nearly top view:
![dn-256-0](https://user-images.githubusercontent.com/56421773/129433123-ddc18b7d-3ad5-4991-9465-02968a70e4ce.png)
My normal map(groundtruth) from nearly top view:
![pred-dn14--2](https://user-images.githubusercontent.com/56421773/129433129-94e8184c-b52b-47c3-9535-a04f14b446cd.png)


Your normal map(groundtruth) from nearly bottom view:
![dn-256-2](https://user-images.githubusercontent.com/56421773/129433142-0637569f-282f-4845-aedd-d0635914a5e7.png)
My normal map(groundtruth) from nearly bottom view:
![pred-dn14--4](https://user-images.githubusercontent.com/56421773/129433148-e7a2773b-4e6a-45e4-a96d-48a004ce6085.png)


Your normal map(groundtruth) from nearly right side view:
![dn-256-8](https://user-images.githubusercontent.com/56421773/129433179-1069ff84-1ab5-419d-8d00-38c31447849e.png)
My normal map(groundtruth) from nearly right side view:
![pred-dn14--10](https://user-images.githubusercontent.com/56421773/129433181-0f2877ae-22a2-40da-a755-dce2d2d552e6.png)


They look from different type.

**Comment by LiuZhenyan-Wuzhong** [comment]
Really thank you.
