### ISSUE TITLE
Run my own sketch

### ISSUE THREAD

**Issue by felipecadar** [happylun/SketchModeling#2]
I would like to run the pipeline on my own airplanes sketches, but I couldn't find any documentation about how to do so, specially in how to setup my view.off file.

**Comment by felipecadar** [comment]
I'm using the same "view.off" file for sketches of the same categories and it seems to be working...

**Comment by felipecadar** [comment]
Found view.off information in the Fusion README
```
view_point_file : an off format mesh file encoding output camera positions in vertex information
```

**Comment by HenriMir** [comment]
According to this, the file view.off only works for 'FS' views, but do you how to change it to make the pipeline work for 'FST' views?, do we only have to add a line '0 2.5 0' at the begining?

**Comment by happylun** [comment]
To clarify, the view.off file only indicates the views in the OUTPUT depth/normal maps, i.e. for each vertex in view.off, it will output a depth/normal map from that view. Those views are independent of the INPUT views i.e. the views of the sketches.
To use your own sketches for training and testing, you will need to specify the ["sketch_views"](https://github.com/happylun/SketchModeling/blob/master/Network/code/MonsterNet/main.py#L51) argument, and change your filenames accordingly. Although I use F/S/T to indicate front/side/top views in my project, they are just names. So in fact you can provide your sketches in side view and back view and name it like sketch-S-0.png sketch-B-0.png and specify "sketch_views" as "SB". As long as you have the same view configuration in your training and testing data, it should be fine (I mean you cannot train your network in front/side view and test it on back/side view).

**Comment by nitish11** [comment]
@happylun : thanks for the clarification. I have two sketches, I named them as sketch-F-0.png sketch-S-0.png and specify "sketch_views" as "FS"

But, I am still getting the error for the below line. 
https://github.com/happylun/SketchModeling/blob/master/Network/code/MonsterNet/main.py#L81
As there is no view.off file, could you please share  a sample view.off file.

**Comment by wangqiang9** [comment]
> @happylun : thanks for the clarification. I have two sketches, I named them as sketch-F-0.png sketch-S-0.png and specify "sketch_views" as "FS"
> 
> But, I am still getting the error for the below line.
> https://github.com/happylun/SketchModeling/blob/master/Network/code/MonsterNet/main.py#L81
> As there is no view.off file, could you please share a sample view.off file.

The TestingData floder have the some `view.off` files, using this `view.off`  files is right?@happylun

**Comment by happylun** [comment]
Yes, using the view.off file from the testing data folder should work.
